import type { AppLanguage } from '../../context/LanguageContext';
import type { CustomSvgLibraryCopy } from './types';

export const customSvgLibraryCopy: CustomSvgLibraryCopy = {
  en: {
    page: {
      highlight: 'Custom SVG',
      title: 'Library',
      description: 'Collect SVG icons, adjust their look, and export exactly the set you need.',
    },
    searchPlaceholder: 'Search icons',
    importSvg: 'Import SVG',
    builtInCount: (count: number) => `${count} built-in icons`,
    importedCount: (count: number) => `${count} imported`,
    showingCount: (count: number) => `${count} showing`,
    downloadZip: 'Download ZIP',
    clearImported: 'Clear imported',
    copiedBanner: 'SVG copied to clipboard.',
    countSummary: (visible: number, total: number) => `${visible} of ${total} icons`,
    emptyTitle: 'No icons found',
    emptyDescription: 'Adjust the query or reset the selected category.',
    clearFilters: 'Clear filters',
    importedBadge: 'imported',
    remove: 'Remove',
    aria: {
      color: 'Icon color',
      size: 'Icon size',
      copy: (name: string) => `Copy ${name} SVG`,
      download: (name: string) => `Download ${name} SVG`,
      remove: (name: string) => `Remove ${name}`,
    },
    status: {
      restored: 'Your saved SVG library is back where you left it.',
      ready: 'Import SVG files or tune the built-in icons to match your UI.',
      clipboardBlocked: 'Clipboard copy was blocked. Download the SVG instead.',
      copied: (name: string) => `${name} SVG copied. You can paste it into your project.`,
      invalid: (fileName: string) => `${fileName} is not a valid SVG file.`,
      added: (fileName: string) => `${fileName} added to your SVG library.`,
      removed: (name: string) => `${name} removed from your SVG library.`,
      customRemoved: 'Custom icon removed.',
      noImported: 'There are no imported SVG icons to clear.',
      cleared: 'Imported SVG icons were cleared from this session.',
      noVisible: 'No visible icons are available to download.',
      packed: (count: number) => `${count} visible SVG files are packed into a ZIP download.`,
    },
    categories: {
      All: 'All',
      Commerce: 'Commerce',
      Communication: 'Communication',
      Custom: 'Custom',
      Navigation: 'Navigation',
      Rating: 'Rating',
      Social: 'Social',
      System: 'System',
      Time: 'Time',
      Users: 'Users',
    },
    iconNames: {
      Calendar: 'Calendar',
      Heart: 'Heart',
      Home: 'Home',
      Mail: 'Mail',
      Settings: 'Settings',
      'Shopping Cart': 'Shopping Cart',
      Star: 'Star',
      'User Circle': 'User Circle',
    },
  },
  ko: {
    page: {
      highlight: '커스텀 SVG',
      title: '라이브러리',
      description: 'SVG 아이콘을 모으고 스타일을 조정한 뒤 필요한 세트만 내보내세요.',
    },
    searchPlaceholder: '아이콘 검색',
    importSvg: 'SVG 가져오기',
    builtInCount: (count: number) => `기본 아이콘 ${count}개`,
    importedCount: (count: number) => `가져온 아이콘 ${count}개`,
    showingCount: (count: number) => `표시 중 ${count}개`,
    downloadZip: 'ZIP 다운로드',
    clearImported: '가져온 아이콘 지우기',
    copiedBanner: 'SVG가 클립보드에 복사되었습니다.',
    countSummary: (visible: number, total: number) => `전체 ${total}개 중 ${visible}개`,
    emptyTitle: '아이콘을 찾지 못했습니다',
    emptyDescription: '검색어를 조정하거나 선택한 카테고리를 초기화하세요.',
    clearFilters: '필터 초기화',
    importedBadge: '가져옴',
    remove: '삭제',
    aria: {
      color: '아이콘 색상',
      size: '아이콘 크기',
      copy: (name: string) => `${name} SVG 복사`,
      download: (name: string) => `${name} SVG 다운로드`,
      remove: (name: string) => `${name} 삭제`,
    },
    status: {
      restored: '저장된 SVG 라이브러리를 다시 불러왔습니다.',
      ready: 'SVG 파일을 가져오거나 기본 아이콘을 UI에 맞게 조정하세요.',
      clipboardBlocked: '클립보드 복사가 차단되었습니다. SVG를 다운로드하세요.',
      copied: (name: string) => `${name} SVG가 복사되었습니다. 프로젝트에 바로 붙여넣을 수 있습니다.`,
      invalid: (fileName: string) => `${fileName}은 올바른 SVG 파일이 아닙니다.`,
      added: (fileName: string) => `${fileName}을 SVG 라이브러리에 추가했습니다.`,
      removed: (name: string) => `${name}을 SVG 라이브러리에서 삭제했습니다.`,
      customRemoved: '커스텀 아이콘을 삭제했습니다.',
      noImported: '지울 가져온 SVG 아이콘이 없습니다.',
      cleared: '이번 세션의 가져온 SVG 아이콘을 모두 지웠습니다.',
      noVisible: '다운로드할 표시 아이콘이 없습니다.',
      packed: (count: number) => `표시 중인 SVG ${count}개를 ZIP으로 묶었습니다.`,
    },
    categories: {
      All: '전체',
      Commerce: '커머스',
      Communication: '커뮤니케이션',
      Custom: '커스텀',
      Navigation: '내비게이션',
      Rating: '평가',
      Social: '소셜',
      System: '시스템',
      Time: '시간',
      Users: '사용자',
    },
    iconNames: {
      Calendar: '캘린더',
      Heart: '하트',
      Home: '홈',
      Mail: '메일',
      Settings: '설정',
      'Shopping Cart': '장바구니',
      Star: '별',
      'User Circle': '사용자 원형',
    },
  },
};

export function getLocalizedIconName(language: AppLanguage, name: string) {
  return customSvgLibraryCopy[language].iconNames[name] ?? name;
}

export function getLocalizedCategory(language: AppLanguage, category: string) {
  return customSvgLibraryCopy[language].categories[category] ?? category;
}
