import type { AppLanguage } from '../../context/LanguageContext';
import type { LogoGeneratorCopy } from './types';

export const logoGeneratorCopy: Record<AppLanguage, LogoGeneratorCopy> = {
  en: {
    aria: {
      copy: (label) => `Copy ${label} SVG`,
      downloadPng: (label) => `Download ${label} PNG`,
      downloadSvg: (label) => `Download ${label} SVG`,
      removeSaved: (label) => `Remove saved ${label}`,
      saveToggle: (saved, label) => `${saved ? 'Remove' : 'Save'} ${label} logo`,
      savedCopy: (label) => `Copy saved ${label} SVG`,
      savedDownload: (label) => `Download saved ${label} SVG`,
    },
    brandName: 'Brand name',
    downloadPngSet: 'Download PNG set',
    downloadSaved: 'Download saved',
    downloadSvgZip: 'Download SVG ZIP',
    emptySaved: 'Save a logo variation to keep it here.',
    optionDescription: 'Ready to copy or download',
    optionLabels: {
      primary: 'Primary',
      variation: (variant) => `Variation ${variant}`,
    },
    page: {
      highlight: 'Logo',
      title: 'Generator',
      description: 'Create quick SVG logo directions, save favorites, and export the files you need.',
    },
    palette: 'Palette',
    paletteLabels: {
      Forest: 'Forest',
      Mono: 'Mono',
      Ocean: 'Ocean',
      Sunset: 'Sunset',
    },
    refresh: 'Refresh variations',
    saved: (count) => `${count} saved`,
    savedDescription: 'Keep favorite SVG concepts and reload their settings later.',
    savedTitle: 'Saved Logos',
    status: {
      allPngReady: 'All current PNG variations are ready to download.',
      allSvgPacked: 'All current SVG variations are packed into a ZIP download.',
      clipboardBlocked: 'Clipboard copy was blocked. Download the SVG instead.',
      copied: (label) => `${label} SVG copied. You can paste it into your project.`,
      copySaved: (label) => `${label} copied from saved logos.`,
      exportPngBatchFailed: 'PNG export did not finish. Try a smaller batch or another browser.',
      exportPngFailed: 'PNG export did not finish. Try another logo variation.',
      favoriteDownloadEmpty: 'Save at least one logo before downloading favorites.',
      favoritePacked: (count) => `${count} saved logo${count === 1 ? '' : 's'} packed into a ZIP download.`,
      loadSaved: (label) => `${label} settings are loaded. You can keep editing from here.`,
      pngReady: (label) => `${label} PNG is ready to download.`,
      ready: 'Choose a style, compare the options, then export the one that fits.',
      refresh: 'Fresh logo variations are ready to review.',
      removed: (label) => `${label} removed from your saved logos.`,
      restored: 'Your saved logo workspace is back where you left it.',
      saved: (label) => `${label} saved for later.`,
      savedRemoved: 'Saved logo removed.',
    },
    style: 'Style',
    styleLabels: {
      Badge: 'Badge',
      Geometric: 'Geometric',
      Minimal: 'Minimal',
      Modern: 'Modern',
    },
    useSettings: 'Use settings',
  },
  ko: {
    aria: {
      copy: (label) => `${label} SVG 복사`,
      downloadPng: (label) => `${label} PNG 다운로드`,
      downloadSvg: (label) => `${label} SVG 다운로드`,
      removeSaved: (label) => `저장된 ${label} 삭제`,
      saveToggle: (saved, label) => `${saved ? '저장 해제' : '저장'} ${label} 로고`,
      savedCopy: (label) => `저장된 ${label} SVG 복사`,
      savedDownload: (label) => `저장된 ${label} SVG 다운로드`,
    },
    brandName: '브랜드 이름',
    downloadPngSet: 'PNG 세트 다운로드',
    downloadSaved: '저장 로고 다운로드',
    downloadSvgZip: 'SVG ZIP 다운로드',
    emptySaved: '로고 변형을 저장하면 여기에 보관됩니다.',
    optionDescription: '복사하거나 다운로드할 준비가 되었습니다',
    optionLabels: {
      primary: '기본안',
      variation: (variant) => `변형 ${variant}`,
    },
    page: {
      highlight: '로고',
      title: '생성기',
      description: '빠르게 SVG 로고 방향을 만들고 즐겨찾기를 저장한 뒤 필요한 파일을 내보내세요.',
    },
    palette: '팔레트',
    paletteLabels: {
      Forest: '포레스트',
      Mono: '모노',
      Ocean: '오션',
      Sunset: '선셋',
    },
    refresh: '변형 새로 만들기',
    saved: (count) => `저장 ${count}개`,
    savedDescription: '마음에 드는 SVG 콘셉트를 보관하고 나중에 설정을 다시 불러오세요.',
    savedTitle: '저장된 로고',
    status: {
      allPngReady: '현재 PNG 변형을 모두 다운로드할 준비가 되었습니다.',
      allSvgPacked: '현재 SVG 변형을 ZIP 다운로드로 묶었습니다.',
      clipboardBlocked: '클립보드 복사가 차단되었습니다. SVG를 다운로드하세요.',
      copied: (label) => `${label} SVG가 복사되었습니다. 프로젝트에 바로 붙여넣을 수 있습니다.`,
      copySaved: (label) => `저장된 ${label}을 복사했습니다.`,
      exportPngBatchFailed: 'PNG 내보내기가 끝나지 않았습니다. 더 작은 묶음이나 다른 브라우저로 시도하세요.',
      exportPngFailed: 'PNG 내보내기가 끝나지 않았습니다. 다른 로고 변형으로 시도하세요.',
      favoriteDownloadEmpty: '저장 로고를 다운로드하려면 로고를 하나 이상 저장하세요.',
      favoritePacked: (count) => `저장된 로고 ${count}개를 ZIP으로 묶었습니다.`,
      loadSaved: (label) => `${label} 설정을 불러왔습니다. 여기서 이어서 편집할 수 있습니다.`,
      pngReady: (label) => `${label} PNG를 다운로드할 준비가 되었습니다.`,
      ready: '스타일을 고르고 옵션을 비교한 뒤 맞는 로고를 내보내세요.',
      refresh: '새 로고 변형을 확인할 수 있습니다.',
      removed: (label) => `${label}을 저장된 로고에서 삭제했습니다.`,
      restored: '저장된 로고 작업공간을 다시 불러왔습니다.',
      saved: (label) => `${label}을 나중에 쓸 수 있게 저장했습니다.`,
      savedRemoved: '저장된 로고를 삭제했습니다.',
    },
    style: '스타일',
    styleLabels: {
      Badge: '배지',
      Geometric: '기하형',
      Minimal: '미니멀',
      Modern: '모던',
    },
    useSettings: '설정 사용',
  },
};
