import type { AppLanguage } from '../../context/LanguageContext';
import type { CleaningCopy, SessionBadge } from './types';

export const cleaningCopy: CleaningCopy = {
  en: {
    addAppointment: 'Add appointment',
    addAppointmentTitle: 'Add appointment',
    addRoom: 'Add room',
    addRoomLabel: 'Add room or area',
    appointmentAdded: (location: string) => `${location} appointment added.`,
    appointmentRemoved: (location: string) => `${location} appointment removed.`,
    appointmentRemovedFallback: 'Appointment removed.',
    appointmentRequired: 'Add a date, location, and cleaner before creating an appointment.',
    appointmentStatusUpdated: 'Appointment status updated.',
    cleaner: 'Cleaner',
    cleanerPlaceholder: 'Cleaner',
    clipboardFailed: 'Clipboard copy failed. Use the notes panel instead.',
    completeAll: 'Mark all complete',
    completeBeforeConfirm: 'Complete every room before confirming the session.',
    completedRooms: (completed: number, total: number) => `${completed} of ${total} rooms completed.`,
    completionNotesDescription: 'Add closeout notes and confirm only after every task is done.',
    completionNotesPlaceholder: 'Write completion notes',
    completionNotesTitle: 'Completion Notes',
    confirmCompletion: 'Confirm Completion',
    copySummary: 'Copy Summary',
    date: 'Date',
    detailLabels: {
      Cleaner: 'Cleaner',
      Location: 'Location',
      Started: 'Started',
    },
    downloadSummary: 'Download Summary',
    exportWorkspace: 'Export Workspace',
    keepOneRoom: 'Keep at least one room in the checklist.',
    location: 'Location',
    markAllComplete: 'All checklist items were marked complete.',
    notes: 'Notes',
    noNotes: 'No notes added.',
    overallProgress: 'Overall Progress',
    pageDescription: 'Track and confirm cleaning tasks and appointments',
    pageHighlight: 'Cleaning Confirmation',
    pageTitle: 'Dashboard',
    pending: 'Pending',
    remove: 'Remove',
    resetDone: 'Cleaning workspace reset to the starter data.',
    resetSession: 'Reset session',
    roomAdded: (room: string) => `${room} added to the checklist.`,
    roomNamePlaceholder: 'Room name',
    roomRequired: 'Add a room or area name before adding a checklist item.',
    roomRemoved: (room: string) => `${room} removed from the checklist.`,
    roomRemovedFallback: 'Checklist item removed.',
    sessionConfirmed: 'Cleaning session confirmed with notes attached.',
    sessionTitle: "Today's Cleaning Session",
    status: {
      Confirmed: 'Confirmed',
      Pending: 'Pending',
    },
    summaryCopied: 'Cleaning summary copied to clipboard.',
    summaryReady: 'Cleaning summary is ready to download.',
    summaryStatus: (confirmed: boolean) => `Cleaning status: ${confirmed ? 'Confirmed' : 'Not confirmed'}`,
    taskChecklist: 'Task Checklist',
    taskUpdated: 'Checklist updated.',
    upcomingAppointmentsDescription: 'Upcoming visits and assigned cleaners.',
    upcomingAppointmentsTitle: 'Upcoming Appointments',
    visitNamePlaceholder: 'Visit name',
    workspaceReady: 'Cleaning workspace is ready to download.',
    workspaceRestored: 'Cleaning workspace restored from local storage.',
    workspaceReadyInitial: 'Tap checklist items as rooms are completed.',
  },
  ko: {
    addAppointment: '방문 일정 추가',
    addAppointmentTitle: '방문 일정 추가',
    addRoom: '공간 추가',
    addRoomLabel: '공간 또는 구역 추가',
    appointmentAdded: (location: string) => `${location} 방문 일정을 추가했습니다.`,
    appointmentRemoved: (location: string) => `${location} 방문 일정을 삭제했습니다.`,
    appointmentRemovedFallback: '방문 일정을 삭제했습니다.',
    appointmentRequired: '방문 일정을 만들려면 날짜, 위치, 담당자를 입력하세요.',
    appointmentStatusUpdated: '방문 일정 상태를 업데이트했습니다.',
    cleaner: '담당자',
    cleanerPlaceholder: '담당자',
    clipboardFailed: '클립보드 복사가 막혔습니다. 메모 패널 내용을 사용하세요.',
    completeAll: '전체 완료',
    completeBeforeConfirm: '세션을 확정하려면 모든 공간을 완료하세요.',
    completedRooms: (completed: number, total: number) => `${total}개 공간 중 ${completed}개 완료`,
    completionNotesDescription: '마감 메모를 남기고 모든 작업이 완료된 뒤에만 확정하세요.',
    completionNotesPlaceholder: '완료 메모 작성',
    completionNotesTitle: '완료 메모',
    confirmCompletion: '완료 확정',
    copySummary: '요약 복사',
    date: '날짜',
    detailLabels: {
      Cleaner: '담당자',
      Location: '위치',
      Started: '시작',
    },
    downloadSummary: '요약 다운로드',
    exportWorkspace: '작업 공간 내보내기',
    keepOneRoom: '체크리스트에는 공간이 하나 이상 있어야 합니다.',
    location: '위치',
    markAllComplete: '모든 체크리스트 항목을 완료로 표시했습니다.',
    notes: '메모',
    noNotes: '메모가 없습니다.',
    overallProgress: '전체 진행률',
    pageDescription: '청소 작업, 방문 일정, 완료 확인을 한곳에서 관리하세요.',
    pageHighlight: '청소 확인',
    pageTitle: '대시보드',
    pending: '대기',
    remove: '삭제',
    resetDone: '청소 확인 작업 공간을 시작 데이터로 초기화했습니다.',
    resetSession: '세션 초기화',
    roomAdded: (room: string) => `${room}을 체크리스트에 추가했습니다.`,
    roomNamePlaceholder: '공간 이름',
    roomRequired: '체크리스트 항목을 추가하려면 공간 또는 구역 이름을 입력하세요.',
    roomRemoved: (room: string) => `${room}을 체크리스트에서 삭제했습니다.`,
    roomRemovedFallback: '체크리스트 항목을 삭제했습니다.',
    sessionConfirmed: '메모와 함께 청소 세션을 확정했습니다.',
    sessionTitle: '오늘의 청소 세션',
    status: {
      Confirmed: '확정됨',
      Pending: '대기',
    },
    summaryCopied: '청소 요약을 클립보드에 복사했습니다.',
    summaryReady: '청소 요약을 다운로드할 수 있습니다.',
    summaryStatus: (confirmed: boolean) => `청소 상태: ${confirmed ? '확정됨' : '미확정'}`,
    taskChecklist: '작업 체크리스트',
    taskUpdated: '체크리스트를 업데이트했습니다.',
    upcomingAppointmentsDescription: '예정된 방문과 배정된 담당자를 확인합니다.',
    upcomingAppointmentsTitle: '예정된 방문 일정',
    visitNamePlaceholder: '방문 이름',
    workspaceReady: '청소 확인 작업 공간을 다운로드할 수 있습니다.',
    workspaceRestored: '로컬 저장소에서 청소 확인 작업 공간을 복원했습니다.',
    workspaceReadyInitial: '완료된 공간을 체크리스트에서 선택하세요.',
  },
};

export const sessionBadgeLabels: Record<AppLanguage, Record<SessionBadge, string>> = {
  en: {
    Confirmed: 'Confirmed',
    'In Progress': 'In Progress',
    'Ready to Confirm': 'Ready to Confirm',
  },
  ko: {
    Confirmed: '확정됨',
    'In Progress': '진행 중',
    'Ready to Confirm': '확정 가능',
  },
};

const cleaningSampleDisplayCopy: Record<string, string> = {
  '09:30 AM': '오전 9:30',
  '10:15 AM': '오전 10:15',
  '11:00 AM': '오전 11:00',
  '123 Main St, Apt 4B': '서울시 마포구 한강로 12, 4B',
  '9:00 AM': '오전 9:00',
  'Apartment Deep Clean': '아파트 대청소',
  'Bathroom 1': '욕실 1',
  'Bedroom 1': '침실 1',
  'Bedroom 2': '침실 2',
  'Entryway supplies restocked. Bedrooms pending final inspection.': '현관 비품을 보충했습니다. 침실은 최종 점검 대기 중입니다.',
  Kitchen: '주방',
  'Laundry Room': '세탁실',
  'Living Room': '거실',
  'Michael Lee': '이민재',
  'Northwind Studio': '노스윈드 스튜디오',
  'Office Maintenance': '사무실 유지 청소',
  'Retail Floor Refresh': '매장 플로어 정리',
  'Sarah Johnson': '김서연',
};

export function getCleaningDisplayText(language: AppLanguage, value: string) {
  return language === 'ko' ? cleaningSampleDisplayCopy[value] ?? value : value;
}

export function getLocalizedTaskTime(language: AppLanguage, time: string) {
  if (time === 'Pending') {
    return cleaningCopy[language].pending;
  }

  return getCleaningDisplayText(language, time);
}
